-- Insert more blog posts
INSERT INTO blogs (title, content, slug, image_path, published_at, created_at, updated_at) VALUES
('Realme GT 6 dengan Charging 150W dan Dimensity 9400','Realme menggebrak pasar flagship killer dengan merilis Realme GT 6, smartphone yang mengedepankan kecepatan dalam segala aspek. Dengan charging 150W UltraDart, baterai 5000mAh pada perangkat ini bisa terisi penuh dalam waktu sekitar 17 menit, menjadikannya salah satu smartphone dengan pengisian tercepat di dunia.

GT 6 ditenagai oleh MediaTek Dimensity 9400, sebuah SoC flagship yang dilengkapi dengan proses fabrikasi 3nm dan performa AI yang tinggi. Benchmark AnTuTu menunjukkan skor di atas 1,5 juta poin, menjadikannya setara dengan flagship kelas atas seperti Snapdragon 8 Gen 4.

Smartphone ini dibekali layar AMOLED 6,74 inci dengan refresh rate 144Hz dan kecerahan hingga 2600 nits, sangat cocok untuk gaming dan outdoor usage. Di sektor kamera, Realme GT 6 membawa kamera utama 50MP dengan OIS, kamera ultrawide 8MP, dan depth sensor 2MP, yang sudah cukup solid untuk kebutuhan fotografi mobile.

Desainnya juga stylish dengan body tipis dan varian warna elegan seperti "Mirage Silver" dan "Aurora Black." Sistem pendingin vapor chamber generasi baru juga disematkan untuk menjaga suhu tetap stabil saat bermain game berat.','realme-gt-6-dengan-charging-150w-dan-dimensity-9400','realme-gt-6-meluncur-dengan-charging-150w-dan-dimensity-9400_image.jpg','2025-05-08 18:39:19','2025-05-08 18:39:19','2025-05-09 13:58:57'),

('ASUS ROG Phone 8 Ultimate: Smartphone Gaming Terbaik 2025','ASUS kembali menjadi raja di ranah smartphone gaming dengan meluncurkan ROG Phone 8 Ultimate, sebuah perangkat yang dirancang khusus untuk gamer hardcore. Tidak hanya menawarkan performa luar biasa, ROG Phone 8 Ultimate juga hadir dengan desain futuristik, layar interaktif mini di belakang, dan ekosistem gaming gear paling lengkap.

Di sektor performa, ponsel ini dipersenjatai Snapdragon 8 Gen 4, dipadukan dengan RAM 24GB dan penyimpanan internal hingga 1TB UFS 4.0. Skor benchmark tinggi ini juga ditunjang oleh sistem pendingin aktif AeroActive Cooler X, yang dapat menurunkan suhu prosesor hingga 10°C saat bermain game berat seperti Genshin Impact atau PUBG Mobile dengan pengaturan rata kanan.

Layar AMOLED 6,78 inci 165Hz dengan touch sampling rate 720Hz dan HDR10+ menjadikan gameplay terasa lebih responsif dan hidup. ASUS juga menyematkan baterai dual-cell 6000mAh dengan pengisian cepat 65W dan dukungan bypass charging saat bermain game — sehingga baterai tidak cepat rusak karena panas.

Tidak ketinggalan, fitur andalan AirTrigger shoulder buttons, RGB lighting, serta software ROG Armoury Crate untuk personalisasi performa dan profil game menambah nilai jual yang sangat tinggi. Kamera utamanya 50MP Sony IMX890 dengan EIS dan kamera ultrawide 13MP membuat ROG Phone 8 Ultimate tetap bisa diandalkan untuk fotografi.','asus-rog-phone-8-ultimate-smartphone-gaming-terbaik-2025','asus-rog-phone-8-ultimate-smartphone-gaming-terbaik-2025_image.jpg','2025-05-08 19:14:08','2025-05-08 19:14:08','2025-05-09 13:58:57'),

('Samsung Galaxy S25 Ultra: Revolusi Kamera dan Kinerja!!','Samsung kembali menunjukkan dominasinya di pasar flagship dengan merilis Galaxy S25 Ultra. Smartphone ini dibekali dengan kamera utama 200 MP yang ditingkatkan dengan teknologi AI Scene Detection generasi keempat, menjadikan hasil foto tetap tajam dan jernih meski dalam kondisi minim cahaya.
Selain itu, Galaxy S25 Ultra ditenagai oleh Exynos 2500 (atau Snapdragon 8 Gen 3 tergantung region), memberikan performa tinggi baik untuk multitasking, gaming, maupun penggunaan profesional seperti pengeditan video 8K. Layarnya menggunakan panel Dynamic AMOLED 2X 6,8 inci dengan refresh rate adaptif hingga 144Hz.
Baterainya berkapasitas 5.500 mAh dan mendukung fast charging 80W, membuatnya sangat andal untuk pemakaian seharian penuh bahkan dalam penggunaan berat. Samsung juga menyematkan fitur AI personal assistant yang lebih pintar dalam mengelola aktivitas dan jadwal pengguna.','samsung-galaxy-s25-ultra-revolusi-kamera-dan-kinerja','samsung-galaxy-s25-ultra-revolusi-kamera-dan-kinerja_image.jpeg','2025-05-09 16:19:20','2025-05-09 16:19:20','2025-05-09 17:09:05'),

('Samsung Galaxy S25 Ultra: Revolusi Kamera dan Kinerja !!','Samsung kembali menunjukkan dominasinya di pasar flagship dengan merilis Galaxy S25 Ultra. Smartphone ini dibekali dengan kamera utama 200 MP yang ditingkatkan dengan teknologi AI Scene Detection generasi keempat, menjadikan hasil foto tetap tajam dan jernih meski dalam kondisi minim cahaya.
Selain itu, Galaxy S25 Ultra ditenagai oleh Exynos 2500 (atau Snapdragon 8 Gen 3 tergantung region), memberikan performa tinggi baik untuk multitasking, gaming, maupun penggunaan profesional seperti pengeditan video 8K. Layarnya menggunakan panel Dynamic AMOLED 2X 6,8 inci dengan refresh rate adaptif hingga 144Hz.
Baterainya berkapasitas 5.500 mAh dan mendukung fast charging 80W, membuatnya sangat andal untuk pemakaian seharian penuh bahkan dalam penggunaan berat. Samsung juga menyematkan fitur AI personal assistant yang lebih pintar dalam mengelola aktivitas dan jadwal pengguna.','samsung-galaxy-s25-ultra-revolusi-kamera-dan-kinerja-1','samsung-galaxy-s25-ultra-revolusi-kamera-dan-kinerja-1_image.jpeg','2025-05-09 19:59:20','2025-05-09 19:59:20','2025-05-09 20:05:46');
